[project]
name = "binary-chords-game"
version = "0.3.0"
description = "A basic Guitar-Hero-like game for practicing using the Binary Chords keyboard"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]
